import type { Metadata } from "next";
import "./globals.css";

/** DB CLASS START */
import User from "../lib/Class/User";
/** DB CLASS END */

/** Component START */
import Header from "../components/layout/Header";
import Footer from "../components/layout/Footer";
/** Component END */

import { SocketProvider } from '@/components/socket-provider'
import { Inter } from 'next/font/google'
// tailwind
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    
    <html lang="ko">
      
      <body>
        <Header />
        <main className="container mx-auto mb-8 mt-10" style={{height:"500px"}}>
          {children}
        </main>
        <Footer />
      </body>

      

    </html>
  );

  //return (
  //  <html lang="en">
  //    <SocketProvider>
  //      <body className={inter.className}>{children}</body>
  //    </SocketProvider>
  //  </html>
  //);
}
