import type { Metadata } from "next";
import "./globals.css";
import User from "../lib/Class/User";
import Header from "../components/layout/Header";
import Footer from "../components/layout/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    
    <html lang="ko">
      
      <body>
        <Header />
        <main>
          {children}
        </main>
        <Footer />
      </body>
      

    </html>
  );
}
